[[PSRIO]]
arch = "x86_64"
git-tree-sha1 = "fda43cedfde1ea7c73da7589e58d0d986c3a6e30"
os = "windows"

    [[PSRIO.download]]
    sha256 = "43e3a2e004d969c357f3db75c427e33c0db6b85589d73a4b65a2cfd5911c3293"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/1741a-3a14e-328cf-43e3a/psrio-distribution-windows.tgz"
[[PSRIO]]
arch = "x86_64"
git-tree-sha1 = "942d5a1b6cdcf98786dea1bf62603bda251628c7"
libc = "glibc"
os = "linux"

    [[PSRIO.download]]
    sha256 = "328cf7ef399c6546246da07cda188ce374db129adf7f77ada39b684cb717f655"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/1741a-3a14e-328cf-43e3a/psrio-distribution-linux.tgz"
[[PSRIO]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "942d5a1b6cdcf98786dea1bf62603bda251628c7"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PSRIO.download]]
    sha256 = "328cf7ef399c6546246da07cda188ce374db129adf7f77ada39b684cb717f655"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/1741a-3a14e-328cf-43e3a/psrio-distribution-linux.tgz"
[[PSRIO]]
arch = "i686"
git-tree-sha1 = "fda43cedfde1ea7c73da7589e58d0d986c3a6e30"
os = "windows"

    [[PSRIO.download]]
    sha256 = "43e3a2e004d969c357f3db75c427e33c0db6b85589d73a4b65a2cfd5911c3293"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/1741a-3a14e-328cf-43e3a/psrio-distribution-windows.tgz"
