[[PSRIO]]
arch = "x86_64"
git-tree-sha1 = "db53f766359660c3bf17153334fb9ce651fbcf7c"
os = "windows"

    [[PSRIO.download]]
    sha256 = "e8073441ff61cf21ade183e83366c8e54fba0db95d160d276a4c36a7df9dcf86"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/c1ef9-6c5ed-578d6-e8073/psrio-distribution-windows.tgz"
[[PSRIO]]
arch = "x86_64"
git-tree-sha1 = "6b5297f07349c2beb8da1b16dd906cc964a0f7d1"
libc = "glibc"
os = "linux"

    [[PSRIO.download]]
    sha256 = "578d6d12c7d51a121bbf3778095d3043e60e84166b4db1c1853c3f62291c9dea"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/c1ef9-6c5ed-578d6-e8073/psrio-distribution-linux.tgz"
[[PSRIO]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6b5297f07349c2beb8da1b16dd906cc964a0f7d1"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PSRIO.download]]
    sha256 = "578d6d12c7d51a121bbf3778095d3043e60e84166b4db1c1853c3f62291c9dea"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/c1ef9-6c5ed-578d6-e8073/psrio-distribution-linux.tgz"
[[PSRIO]]
arch = "i686"
git-tree-sha1 = "db53f766359660c3bf17153334fb9ce651fbcf7c"
os = "windows"

    [[PSRIO.download]]
    sha256 = "e8073441ff61cf21ade183e83366c8e54fba0db95d160d276a4c36a7df9dcf86"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/c1ef9-6c5ed-578d6-e8073/psrio-distribution-windows.tgz"
