[[PSRIO]]
arch = "x86_64"
git-tree-sha1 = "1bd0edc9cbc2cbc53bd703f4b9ed3b9c417c1af6"
os = "windows"

    [[PSRIO.download]]
    sha256 = "0e2566a6eb74dd7860e037bf68fb5a6b8a7ae157cb6f2f6e1eb9eb017b2b4bce"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/fbb4e-b7d8c-a01dc-0e256/psrio-distribution-windows.tgz"
[[PSRIO]]
arch = "x86_64"
git-tree-sha1 = "5a9c37d5e27412c3496858b49a2658dc9aec8ce6"
libc = "glibc"
os = "linux"

    [[PSRIO.download]]
    sha256 = "a01dcac14ad6c6a45903ad61074db66dbf84e962ba14b64020e94513641aa0ee"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/fbb4e-b7d8c-a01dc-0e256/psrio-distribution-linux.tgz"
[[PSRIO]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5a9c37d5e27412c3496858b49a2658dc9aec8ce6"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PSRIO.download]]
    sha256 = "a01dcac14ad6c6a45903ad61074db66dbf84e962ba14b64020e94513641aa0ee"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/fbb4e-b7d8c-a01dc-0e256/psrio-distribution-linux.tgz"
[[PSRIO]]
arch = "i686"
git-tree-sha1 = "1bd0edc9cbc2cbc53bd703f4b9ed3b9c417c1af6"
os = "windows"

    [[PSRIO.download]]
    sha256 = "0e2566a6eb74dd7860e037bf68fb5a6b8a7ae157cb6f2f6e1eb9eb017b2b4bce"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/fbb4e-b7d8c-a01dc-0e256/psrio-distribution-windows.tgz"
