[[PSRIO]]
arch = "i686"
git-tree-sha1 = "81c0762733bc81df824260af5639106ab9337798"
os = "windows"

    [[PSRIO.download]]
    sha256 = "7141e27cc2d49b7a42318b7d0a8a95f5e40b1096b4a57f2a788ae06a50f155bf"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/7141e-e247d/psrio-distribution-windows.tgz"
[[PSRIO]]
arch = "x86_64"
git-tree-sha1 = "6ab27e0fa2baf55f76e17751dc1f744f5e121cb2"
os = "windows"

    [[PSRIO.download]]
    sha256 = "feabbc9c9dd57e0ec65da1d8b1b7a2e088d10528531a9a1612d011641e68ba37"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/feabb-edaef/psrio-distribution-windows.tgz"
[[PSRIO]]
arch = "x86_64"
git-tree-sha1 = "67dc58320dba61fb8cdd1df8e4a6fa8fdcec23c8"
libc = "glibc"
os = "linux"

    [[PSRIO.download]]
    sha256 = "edaef62c201e9f7d0067ed5977d312e968ce5969d8a85a05fd4876b9ce3f4757"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/feabb-edaef/psrio-distribution-linux.tgz"
