[[PSRIO]]
arch = "x86_64"
git-tree-sha1 = "ab54e6f70191a50d1a2ad7861a3d43d4afbdb635"
os = "windows"

    [[PSRIO.download]]
    sha256 = "439850286ba09e0997c933f50bcd16c4931e1081f0eaeeaa88ddfcd7933ee455"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/f2b78-a850f-8e309-43985/psrio-distribution-windows.tgz"
[[PSRIO]]
arch = "x86_64"
git-tree-sha1 = "c8ff85cec4ebd4c7e50b74d9e80568900d73c243"
libc = "glibc"
os = "linux"

    [[PSRIO.download]]
    sha256 = "8e309965c80e6f7c025022306ba58dc38d41b83cfdd09b9e36d90d58b0635791"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/f2b78-a850f-8e309-43985/psrio-distribution-linux.tgz"
[[PSRIO]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c8ff85cec4ebd4c7e50b74d9e80568900d73c243"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PSRIO.download]]
    sha256 = "8e309965c80e6f7c025022306ba58dc38d41b83cfdd09b9e36d90d58b0635791"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/f2b78-a850f-8e309-43985/psrio-distribution-linux.tgz"
[[PSRIO]]
arch = "i686"
git-tree-sha1 = "ab54e6f70191a50d1a2ad7861a3d43d4afbdb635"
os = "windows"

    [[PSRIO.download]]
    sha256 = "439850286ba09e0997c933f50bcd16c4931e1081f0eaeeaa88ddfcd7933ee455"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/f2b78-a850f-8e309-43985/psrio-distribution-windows.tgz"
