[[PSRIO]]
arch = "i686"
git-tree-sha1 = "81c0762733bc81df824260af5639106ab9337798"
os = "windows"

    [[PSRIO.download]]
    sha256 = "7141e27cc2d49b7a42318b7d0a8a95f5e40b1096b4a57f2a788ae06a50f155bf"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/7141e-e247d/psrio-distribution-windows.tgz"
[[PSRIO]]
arch = "x86_64"
git-tree-sha1 = "ff589efaabea175c112d3422a7a277764fc431dd"
os = "windows"

    [[PSRIO.download]]
    sha256 = "16cc1c31dac16b4841c38d1bc1d96c73407e6ff1299d712150cecd4d7b872390"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/16cc1-af126/psrio-distribution-windows.tgz"
[[PSRIO]]
arch = "x86_64"
git-tree-sha1 = "07393c010434d9aa1b4c79e8a70758c2f65cb350"
libc = "glibc"
os = "linux"

    [[PSRIO.download]]
    sha256 = "af126ebfa6dd6f73d02c40e00f14024b6f0efcca6a1c6267b4b225c97f41836e"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/16cc1-af126/psrio-distribution-linux.tgz"
