[[PSRIO]]
arch = "i686"
git-tree-sha1 = "81c0762733bc81df824260af5639106ab9337798"
os = "windows"

    [[PSRIO.download]]
    sha256 = "7141e27cc2d49b7a42318b7d0a8a95f5e40b1096b4a57f2a788ae06a50f155bf"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/7141e-e247d/psrio-distribution-windows.tgz"
[[PSRIO]]
arch = "x86_64"
git-tree-sha1 = "fb9602d379bd6cace5027bf5d55981094145a31b"
os = "windows"

    [[PSRIO.download]]
    sha256 = "e779561602eb1477ebcc3cd9a4e8f2d71eebcb90e1e35d04bc0d77d83f90f324"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/e7795-8cd26/psrio-distribution-windows.tgz"
[[PSRIO]]
arch = "x86_64"
git-tree-sha1 = "e3fd62addbd203146e657d15665d3060d681a82b"
libc = "glibc"
os = "linux"

    [[PSRIO.download]]
    sha256 = "8cd26a85fea622f88cc162c9f85c2f1a60db5fd1d14b88dfbd18e29b249af475"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/e7795-8cd26/psrio-distribution-linux.tgz"
