[[PSRIO]]
arch = "i686"
git-tree-sha1 = "81c0762733bc81df824260af5639106ab9337798"
os = "windows"

    [[PSRIO.download]]
    sha256 = "7141e27cc2d49b7a42318b7d0a8a95f5e40b1096b4a57f2a788ae06a50f155bf"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/7141e-e247d/psrio-distribution-windows.tgz"
[[PSRIO]]
arch = "x86_64"
git-tree-sha1 = "ff589efaabea175c112d3422a7a277764fc431dd"
os = "windows"

    [[PSRIO.download]]
    sha256 = "40b7022c2d87c8055b26a862654abcafb16c1ca2f26e22abe320c2ab3649105a"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/40b70-22d46/psrio-distribution-windows.tgz"
[[PSRIO]]
arch = "x86_64"
git-tree-sha1 = "07393c010434d9aa1b4c79e8a70758c2f65cb350"
libc = "glibc"
os = "linux"

    [[PSRIO.download]]
    sha256 = "22d4609c7f1a0b99755396b501d22c55bee5bdc2e27513caebe49796647674b2"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/40b70-22d46/psrio-distribution-linux.tgz"
