[[PSRIO]]
arch = "x86_64"
git-tree-sha1 = "11ff0f03044f43a7a5257e6d6294bc1e4aef3622"
os = "windows"

    [[PSRIO.download]]
    sha256 = "f2f602668636b4ef25948e9f053bfe7ee92f3d456b6420b769b3ea401ed03dc2"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/2d710-1c65d-ead11-f2f60/psrio-distribution-windows.tgz"
[[PSRIO]]
arch = "x86_64"
git-tree-sha1 = "5a9c37d5e27412c3496858b49a2658dc9aec8ce6"
libc = "glibc"
os = "linux"

    [[PSRIO.download]]
    sha256 = "ead119c8cecbbb7fcdf8fb788afa6d5bdff7c715c81ca5bfd20321080d09eba7"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/2d710-1c65d-ead11-f2f60/psrio-distribution-linux.tgz"
[[PSRIO]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5a9c37d5e27412c3496858b49a2658dc9aec8ce6"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PSRIO.download]]
    sha256 = "ead119c8cecbbb7fcdf8fb788afa6d5bdff7c715c81ca5bfd20321080d09eba7"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/2d710-1c65d-ead11-f2f60/psrio-distribution-linux.tgz"
[[PSRIO]]
arch = "i686"
git-tree-sha1 = "11ff0f03044f43a7a5257e6d6294bc1e4aef3622"
os = "windows"

    [[PSRIO.download]]
    sha256 = "f2f602668636b4ef25948e9f053bfe7ee92f3d456b6420b769b3ea401ed03dc2"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/2d710-1c65d-ead11-f2f60/psrio-distribution-windows.tgz"
