[[PSRIO]]
arch = "i686"
git-tree-sha1 = "81c0762733bc81df824260af5639106ab9337798"
os = "windows"

    [[PSRIO.download]]
    sha256 = "7141e27cc2d49b7a42318b7d0a8a95f5e40b1096b4a57f2a788ae06a50f155bf"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/7141e-e247d/psrio-distribution-windows.tgz"
[[PSRIO]]
arch = "x86_64"
git-tree-sha1 = "fb9602d379bd6cace5027bf5d55981094145a31b"
os = "windows"

    [[PSRIO.download]]
    sha256 = "ea18decf69953f2ddfbb2c3fe145dc6a2386ec317b765813d775e81522086948"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/ea18d-d4e4a/psrio-distribution-windows.tgz"
[[PSRIO]]
arch = "x86_64"
git-tree-sha1 = "e3fd62addbd203146e657d15665d3060d681a82b"
libc = "glibc"
os = "linux"

    [[PSRIO.download]]
    sha256 = "d4e4a80cd3a89d377252ea3b9dc03097c2010d9a7e351d55090ee51e137a5b21"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/ea18d-d4e4a/psrio-distribution-linux.tgz"
