[[PSRIO]]
arch = "i686"
git-tree-sha1 = "81c0762733bc81df824260af5639106ab9337798"
os = "windows"

    [[PSRIO.download]]
    sha256 = "7141e27cc2d49b7a42318b7d0a8a95f5e40b1096b4a57f2a788ae06a50f155bf"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/7141e-e247d/psrio-distribution-windows.tgz"
[[PSRIO]]
arch = "x86_64"
git-tree-sha1 = "a11d95e631722526d1e4691b91ac3fd77d07c4c0"
os = "windows"

    [[PSRIO.download]]
    sha256 = "27fd769ba768a2caee92e501746f0d3dd52d80dcddf145381ef083e970e719fa"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/27fd7-dfb6e/psrio-distribution-windows.tgz"
[[PSRIO]]
arch = "x86_64"
git-tree-sha1 = "838af80dc476ca59726e06d10d92e301fc5c23a4"
libc = "glibc"
os = "linux"

    [[PSRIO.download]]
    sha256 = "dfb6e163cd85c2ad32d8d8c953c2b79410f8e8bf7b222b65a8e7dcad774de8cf"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/27fd7-dfb6e/psrio-distribution-linux.tgz"
