[[PSRIO]]
arch = "i686"
git-tree-sha1 = "81c0762733bc81df824260af5639106ab9337798"
os = "windows"

    [[PSRIO.download]]
    sha256 = "7141e27cc2d49b7a42318b7d0a8a95f5e40b1096b4a57f2a788ae06a50f155bf"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/7141e-e247d/psrio-distribution-windows.tgz"
[[PSRIO]]
arch = "x86_64"
git-tree-sha1 = "6ec306abab911782f2d1fcf0f18735dcfae3365a"
os = "windows"

    [[PSRIO.download]]
    sha256 = "50b34916fb1503e3bfa3c464a49ee6cef7a3512e60d91f11644aa31c116e1c12"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/50b34-7ad69/psrio-distribution-windows.tgz"
[[PSRIO]]
arch = "x86_64"
git-tree-sha1 = "4f87f726ca0593e2fca094c04eff3c25ce347fa5"
libc = "glibc"
os = "linux"

    [[PSRIO.download]]
    sha256 = "7ad692f2a48e484193d63f179ecee090946062c9ccd849bef019f0a3bce23e89"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/50b34-7ad69/psrio-distribution-linux.tgz"
