[[PSRIO]]
arch = "i686"
git-tree-sha1 = "81c0762733bc81df824260af5639106ab9337798"
os = "windows"

    [[PSRIO.download]]
    sha256 = "7141e27cc2d49b7a42318b7d0a8a95f5e40b1096b4a57f2a788ae06a50f155bf"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/7141e-e247d/psrio-distribution-windows.tgz"
[[PSRIO]]
arch = "x86_64"
git-tree-sha1 = "4d104c5d74a317d7fb29768c7d5222bfd167ac62"
os = "windows"

    [[PSRIO.download]]
    sha256 = "57dae960f4fa957321049ce69e05f041c6a3fb1119df934063f85fabb99d2445"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/57dae-00036/psrio-distribution-windows.tgz"
[[PSRIO]]
arch = "x86_64"
git-tree-sha1 = "15c254f217c09aec5dc56b6afeeda63720790e24"
libc = "glibc"
os = "linux"

    [[PSRIO.download]]
    sha256 = "000364277d4e66ce19906c03d680fcc282a6c4e79146f463d0874fd88aeacfee"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/57dae-00036/psrio-distribution-linux.tgz"
