[[PSRIO]]
arch = "i686"
git-tree-sha1 = "81c0762733bc81df824260af5639106ab9337798"
os = "windows"

    [[PSRIO.download]]
    sha256 = "7141e27cc2d49b7a42318b7d0a8a95f5e40b1096b4a57f2a788ae06a50f155bf"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/7141e-e247d/psrio-distribution-windows.tgz"
[[PSRIO]]
arch = "x86_64"
git-tree-sha1 = "e3965e340cb3ee9a3f0e3252d24dadfe9a8d3569"
os = "windows"

    [[PSRIO.download]]
    sha256 = "566a0dfec80c0b17cb949e48994edb3177f7831e860bf590d521862fd5130552"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/566a0-5084c/psrio-distribution-windows.tgz"
[[PSRIO]]
arch = "x86_64"
git-tree-sha1 = "a1aed6e78573d624ac7b8524de48eddf16ed56ca"
libc = "glibc"
os = "linux"

    [[PSRIO.download]]
    sha256 = "5084c9757ebdc953ac3bb65c473bc1e52c6acfa5de515558c70508425685fee3"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/566a0-5084c/psrio-distribution-linux.tgz"
