[[PSRIO]]
arch = "i686"
git-tree-sha1 = "81c0762733bc81df824260af5639106ab9337798"
os = "windows"

    [[PSRIO.download]]
    sha256 = "7141e27cc2d49b7a42318b7d0a8a95f5e40b1096b4a57f2a788ae06a50f155bf"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/7141e-e247d/psrio-distribution-windows.tgz"
[[PSRIO]]
arch = "x86_64"
git-tree-sha1 = "68f329a03204f9bfc530118a25f2d3794e6cf447"
os = "windows"

    [[PSRIO.download]]
    sha256 = "4ecc6af10d83c6cc60a5a25e82d49ea9e34b47915709f30ca43cb6435b2a5376"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/4ecc6-acfd3/psrio-distribution-windows.tgz"
[[PSRIO]]
arch = "x86_64"
git-tree-sha1 = "74761a4c8de9687b9d67fe031a06b1ca5de032a1"
libc = "glibc"
os = "linux"

    [[PSRIO.download]]
    sha256 = "acfd3c75f8b3bda437f92691e865a67a8639ac91fe9917bd3f37aaba546fafe8"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/4ecc6-acfd3/psrio-distribution-linux.tgz"
