[[PSRIO]]
arch = "x86_64"
git-tree-sha1 = "f9e64716dba77f12b199834d22b08e407885822d"
os = "windows"

    [[PSRIO.download]]
    sha256 = "01852644f374c2ee1837c58835f50a00163abdbc47e9e8e9d6e1ae153e807351"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/cf679-c29af-cd5ec-01852/psrio-distribution-windows.tgz"
[[PSRIO]]
arch = "x86_64"
git-tree-sha1 = "0eaf0ce46b27113fbbf44f7273f81a87e591cca1"
libc = "glibc"
os = "linux"

    [[PSRIO.download]]
    sha256 = "cd5ec56a81afd637454fd6c390aa78521d7faa298e9f9962e9bd89fcb5e0be4c"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/cf679-c29af-cd5ec-01852/psrio-distribution-linux.tgz"
[[PSRIO]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0eaf0ce46b27113fbbf44f7273f81a87e591cca1"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PSRIO.download]]
    sha256 = "cd5ec56a81afd637454fd6c390aa78521d7faa298e9f9962e9bd89fcb5e0be4c"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/cf679-c29af-cd5ec-01852/psrio-distribution-linux.tgz"
[[PSRIO]]
arch = "i686"
git-tree-sha1 = "f9e64716dba77f12b199834d22b08e407885822d"
os = "windows"

    [[PSRIO.download]]
    sha256 = "01852644f374c2ee1837c58835f50a00163abdbc47e9e8e9d6e1ae153e807351"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/cf679-c29af-cd5ec-01852/psrio-distribution-windows.tgz"
