[[PSRIO]]
arch = "i686"
git-tree-sha1 = "81c0762733bc81df824260af5639106ab9337798"
os = "windows"

    [[PSRIO.download]]
    sha256 = "7141e27cc2d49b7a42318b7d0a8a95f5e40b1096b4a57f2a788ae06a50f155bf"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/7141e-e247d/psrio-distribution-windows.tgz"
[[PSRIO]]
arch = "x86_64"
git-tree-sha1 = "cbe62afedf73b6b809860647b1f72c9848144b77"
os = "windows"

    [[PSRIO.download]]
    sha256 = "cc0916f7457e52658a4f91c8da34b8c53b012da8474ec16d47ae0a1da8320d4c"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/cc091-fcedc/psrio-distribution-windows.tgz"
[[PSRIO]]
arch = "x86_64"
git-tree-sha1 = "3c8c7c98021302c637a42d938108f5d72ba28be0"
libc = "glibc"
os = "linux"

    [[PSRIO.download]]
    sha256 = "fcedc6b89dfa842a1fd1a4478bda6464d72e825fac8e90a688ab204d25d08e5a"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/cc091-fcedc/psrio-distribution-linux.tgz"
