[[PSRIO]]
arch = "x86_64"
git-tree-sha1 = "2f39709269fd31a267b11efd59dec4e25a0577d0"
os = "windows"

    [[PSRIO.download]]
    sha256 = "a348484eb08eeef84f16d68d2bbef0dd85e51fd77f08e1fa5e53bd4a311c581d"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/8d644-91f2f-33a14-a3484/psrio-distribution-windows.tgz"
[[PSRIO]]
arch = "x86_64"
git-tree-sha1 = "a98e98dccd5a8143f3c9f993d0c971e946087869"
libc = "glibc"
os = "linux"

    [[PSRIO.download]]
    sha256 = "33a14fd4dff5b72700fae2f358b99e8f8794f459b107f369d1b6578153b5fb17"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/8d644-91f2f-33a14-a3484/psrio-distribution-linux.tgz"
[[PSRIO]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a98e98dccd5a8143f3c9f993d0c971e946087869"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PSRIO.download]]
    sha256 = "33a14fd4dff5b72700fae2f358b99e8f8794f459b107f369d1b6578153b5fb17"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/8d644-91f2f-33a14-a3484/psrio-distribution-linux.tgz"
[[PSRIO]]
arch = "i686"
git-tree-sha1 = "2f39709269fd31a267b11efd59dec4e25a0577d0"
os = "windows"

    [[PSRIO.download]]
    sha256 = "a348484eb08eeef84f16d68d2bbef0dd85e51fd77f08e1fa5e53bd4a311c581d"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/8d644-91f2f-33a14-a3484/psrio-distribution-windows.tgz"
