[[PSRIO]]
arch = "x86_64"
git-tree-sha1 = "fc9f8f516ea9fa5e51079ccc016f6dd439e0b7b7"
os = "windows"

    [[PSRIO.download]]
    sha256 = "a1048b66b812e677036be36a06abde036eb6e02b6c7f2ad1b26741cfc35c2f83"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/20c91-c444b-9628a-a1048/psrio-distribution-windows.tgz"
[[PSRIO]]
arch = "x86_64"
git-tree-sha1 = "f35fa8baa5123350cc71efae23f8756002e28586"
libc = "glibc"
os = "linux"

    [[PSRIO.download]]
    sha256 = "9628ae5ad64748a3eb54128546957506ebf8c18ec34d04e9f81de18cbb45169c"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/20c91-c444b-9628a-a1048/psrio-distribution-linux.tgz"
[[PSRIO]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f35fa8baa5123350cc71efae23f8756002e28586"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PSRIO.download]]
    sha256 = "9628ae5ad64748a3eb54128546957506ebf8c18ec34d04e9f81de18cbb45169c"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/20c91-c444b-9628a-a1048/psrio-distribution-linux.tgz"
[[PSRIO]]
arch = "i686"
git-tree-sha1 = "fc9f8f516ea9fa5e51079ccc016f6dd439e0b7b7"
os = "windows"

    [[PSRIO.download]]
    sha256 = "a1048b66b812e677036be36a06abde036eb6e02b6c7f2ad1b26741cfc35c2f83"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/20c91-c444b-9628a-a1048/psrio-distribution-windows.tgz"
