[[PSRIO]]
arch = "x86_64"
git-tree-sha1 = "4fcf275370b322fa1cf44c92789b220c109559cd"
os = "windows"

    [[PSRIO.download]]
    sha256 = "0e5db6729cc08fd2939f52c377fca3197f1c63fd4b44f83a90330eaf36cee61d"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/0c239-1cdbc-ca45d-0e5db/psrio-distribution-windows.tgz"
[[PSRIO]]
arch = "x86_64"
git-tree-sha1 = "a14f071ae7fc4be6e6a3c670d99eb8ff539fb5e4"
libc = "glibc"
os = "linux"

    [[PSRIO.download]]
    sha256 = "ca45db5d6e687fc35cabdd4e46dc3592a6e3ebf092a7df0a0981941d66b8b051"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/0c239-1cdbc-ca45d-0e5db/psrio-distribution-linux.tgz"
[[PSRIO]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a14f071ae7fc4be6e6a3c670d99eb8ff539fb5e4"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PSRIO.download]]
    sha256 = "ca45db5d6e687fc35cabdd4e46dc3592a6e3ebf092a7df0a0981941d66b8b051"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/0c239-1cdbc-ca45d-0e5db/psrio-distribution-linux.tgz"
[[PSRIO]]
arch = "i686"
git-tree-sha1 = "4fcf275370b322fa1cf44c92789b220c109559cd"
os = "windows"

    [[PSRIO.download]]
    sha256 = "0e5db6729cc08fd2939f52c377fca3197f1c63fd4b44f83a90330eaf36cee61d"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/0c239-1cdbc-ca45d-0e5db/psrio-distribution-windows.tgz"
