[[PSRIO]]
arch = "i686"
git-tree-sha1 = "81c0762733bc81df824260af5639106ab9337798"
os = "windows"

    [[PSRIO.download]]
    sha256 = "7141e27cc2d49b7a42318b7d0a8a95f5e40b1096b4a57f2a788ae06a50f155bf"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/7141e-e247d/psrio-distribution-windows.tgz"
[[PSRIO]]
arch = "x86_64"
git-tree-sha1 = "6ab27e0fa2baf55f76e17751dc1f744f5e121cb2"
os = "windows"

    [[PSRIO.download]]
    sha256 = "1be7e4dda730594ca528cebfd05088630128cef15c4ce2acdf81b44fd77bf727"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/1be7e-ae9b8/psrio-distribution-windows.tgz"
[[PSRIO]]
arch = "x86_64"
git-tree-sha1 = "67dc58320dba61fb8cdd1df8e4a6fa8fdcec23c8"
libc = "glibc"
os = "linux"

    [[PSRIO.download]]
    sha256 = "ae9b8497330efd8ebae33d2246d77181970b2c8af7ed613da850b234fcc4230c"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/1be7e-ae9b8/psrio-distribution-linux.tgz"
