[[PSRIO]]
arch = "i686"
git-tree-sha1 = "81c0762733bc81df824260af5639106ab9337798"
os = "windows"

    [[PSRIO.download]]
    sha256 = "7141e27cc2d49b7a42318b7d0a8a95f5e40b1096b4a57f2a788ae06a50f155bf"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/7141e-e247d/psrio-distribution-windows.tgz"
[[PSRIO]]
arch = "x86_64"
git-tree-sha1 = "a29883ebddd19febc8b81eaa5119c239a4bdf359"
os = "windows"

    [[PSRIO.download]]
    sha256 = "c2e3aaa12268cb26ba35188f758a46d34af1a304ba0eaaccc05abcb242b0b437"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/c2e3a-764cf/psrio-distribution-windows.tgz"
[[PSRIO]]
arch = "x86_64"
git-tree-sha1 = "5bce403e5a5fed1e91b8ca234df3c558a5c4a395"
libc = "glibc"
os = "linux"

    [[PSRIO.download]]
    sha256 = "764cfb327b3274b22342bf1f23e143995e798c568880dbdab154c01b5cd0858b"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/c2e3a-764cf/psrio-distribution-linux.tgz"
