[[PSRIO]]
arch = "i686"
git-tree-sha1 = "81c0762733bc81df824260af5639106ab9337798"
os = "windows"

    [[PSRIO.download]]
    sha256 = "7141e27cc2d49b7a42318b7d0a8a95f5e40b1096b4a57f2a788ae06a50f155bf"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/7141e-e247d/psrio-distribution-windows.tgz"
[[PSRIO]]
arch = "x86_64"
git-tree-sha1 = "e2b60f85bdf29f0ecb75001fdcd05b75d8145459"
os = "windows"

    [[PSRIO.download]]
    sha256 = "0d093ac68e2e41e6c93411abfe874875cee5cded1021b899a537d28805d92dda"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/0d093-e4ed1/psrio-distribution-windows.tgz"
[[PSRIO]]
arch = "x86_64"
git-tree-sha1 = "bb42bdc20070dafde9d2494f62cfc01366b1f665"
libc = "glibc"
os = "linux"

    [[PSRIO.download]]
    sha256 = "e4ed1b550000427fb2b28e1c2b9858771f1374d77bacab6c39c914d01e3846ed"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/0d093-e4ed1/psrio-distribution-linux.tgz"
