[[PSRIO]]
arch = "x86_64"
git-tree-sha1 = "80f5c1a5d05e63142afb144296a5af4037e5d8dd"
os = "windows"

    [[PSRIO.download]]
    sha256 = "7ecd2ee14b3f90baa1cbce5e6303c66927138dcf4c617add3a6015818a2907cc"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/f9e0f-b7e53-67f88-7ecd2/psrio-distribution-windows.tgz"
[[PSRIO]]
arch = "x86_64"
git-tree-sha1 = "bd023a3480e0616a669575768b1a60457ae3c0bc"
libc = "glibc"
os = "linux"

    [[PSRIO.download]]
    sha256 = "67f8841e120be7f1afd0312e7d37b6f3735400d3d264e6e0e2f792ce72b8ef16"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/f9e0f-b7e53-67f88-7ecd2/psrio-distribution-linux.tgz"
[[PSRIO]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bd023a3480e0616a669575768b1a60457ae3c0bc"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PSRIO.download]]
    sha256 = "67f8841e120be7f1afd0312e7d37b6f3735400d3d264e6e0e2f792ce72b8ef16"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/f9e0f-b7e53-67f88-7ecd2/psrio-distribution-linux.tgz"
[[PSRIO]]
arch = "i686"
git-tree-sha1 = "80f5c1a5d05e63142afb144296a5af4037e5d8dd"
os = "windows"

    [[PSRIO.download]]
    sha256 = "7ecd2ee14b3f90baa1cbce5e6303c66927138dcf4c617add3a6015818a2907cc"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/f9e0f-b7e53-67f88-7ecd2/psrio-distribution-windows.tgz"
