[[PSRIO]]
arch = "i686"
git-tree-sha1 = "81c0762733bc81df824260af5639106ab9337798"
os = "windows"

    [[PSRIO.download]]
    sha256 = "7141e27cc2d49b7a42318b7d0a8a95f5e40b1096b4a57f2a788ae06a50f155bf"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/7141e-e247d/psrio-distribution-windows.tgz"
[[PSRIO]]
arch = "x86_64"
git-tree-sha1 = "fc9f8f516ea9fa5e51079ccc016f6dd439e0b7b7"
os = "windows"

    [[PSRIO.download]]
    sha256 = "2b6eac783979e108aa5b3984d479b8127e6c2918f204a9fff6e94e7338e9138e"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/2b6ea-cc62b/psrio-distribution-windows.tgz"
[[PSRIO]]
arch = "x86_64"
git-tree-sha1 = "7bebe7eac0f3a249b5e0fe5add00e4e7d449d438"
libc = "glibc"
os = "linux"

    [[PSRIO.download]]
    sha256 = "cc62b78cab1b1987f38cefc0319bd4cb000ff719d27e9e17051a7c5eef9114dc"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/2b6ea-cc62b/psrio-distribution-linux.tgz"
