[[PSRIO]]
arch = "i686"
git-tree-sha1 = "81c0762733bc81df824260af5639106ab9337798"
os = "windows"

    [[PSRIO.download]]
    sha256 = "7141e27cc2d49b7a42318b7d0a8a95f5e40b1096b4a57f2a788ae06a50f155bf"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/7141e-e247d/psrio-distribution-windows.tgz"
[[PSRIO]]
arch = "x86_64"
git-tree-sha1 = "6ec306abab911782f2d1fcf0f18735dcfae3365a"
os = "windows"

    [[PSRIO.download]]
    sha256 = "973bc11d01f36d3c03bd2f577e1967f99f065313eadf2263382634906e2229b3"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/973bc-8d904/psrio-distribution-windows.tgz"
[[PSRIO]]
arch = "x86_64"
git-tree-sha1 = "4f87f726ca0593e2fca094c04eff3c25ce347fa5"
libc = "glibc"
os = "linux"

    [[PSRIO.download]]
    sha256 = "8d904aad011128702f6939d0826d57ed990f26427f059d511206741f14ebff1a"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/973bc-8d904/psrio-distribution-linux.tgz"
