[[PSRIO]]
arch = "i686"
git-tree-sha1 = "81c0762733bc81df824260af5639106ab9337798"
os = "windows"

    [[PSRIO.download]]
    sha256 = "7141e27cc2d49b7a42318b7d0a8a95f5e40b1096b4a57f2a788ae06a50f155bf"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/7141e-e247d/psrio-distribution-windows.tgz"
[[PSRIO]]
arch = "x86_64"
git-tree-sha1 = "d218ec4de7c34b506bff92af642911a39f2e8023"
os = "windows"

    [[PSRIO.download]]
    sha256 = "d402dd42d0d30e4edaf42a1ef02e71297bc026a5e90a5d77812130b467f55244"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/d402d-ef294/psrio-distribution-windows.tgz"
[[PSRIO]]
arch = "x86_64"
git-tree-sha1 = "ab203813808c797d8eaf55f1ca21529871a46474"
libc = "glibc"
os = "linux"

    [[PSRIO.download]]
    sha256 = "ef2946c8a98e0720f362852ab0c405ec600f3e358795b3a8d20f94a87c4c71f2"
    url = "https://julia-artifacts.s3.amazonaws.com/psrio-distribution/d402d-ef294/psrio-distribution-linux.tgz"
