name = "PSRIO"
uuid = "28cd61d8-bd87-4892-a734-3497164865b3"
version = "2.2.0-beta"

[deps]
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
